### ISSUE TITLE
'function' object has no attribute 'urlencode'

### ISSUE THREAD

**Issue by Lumonike** [VadVergasov/CodeforcesApiPy#416]
**Describe the bug**
I installed the package into a virtual environment and proceeded to attempt the following code:
```
import codeforces_api
import json

SECRETS = json.load(open("secret.json"))

cf_api = codeforces_api.CodeforcesApi(api_key = SECRETS["key"], secret = SECRETS["secret"])

print(cf_api.contest_list(gym = True))
```

which of course raised the error

```
Traceback (most recent call last):
  File "/root/lumonike/cf_api/main.py", line 8, in <module>
    print(cf_api.contest_list(gym = True))
  File "/root/lumonike/cf_api/env/lib/python3.10/site-packages/codeforces_api/api_requests.py", line 112, in contest_list
    for contest in self._make_request(
  File "/root/lumonike/cf_api/env/lib/python3.10/site-packages/codeforces_api/api_requests.py", line 49, in _make_request
    request_data = self.generate_request(method, **payload)
  File "/root/lumonike/cf_api/env/lib/python3.10/site-packages/codeforces_api/api_request_maker.py", line 71, in generate_request
    api_signature += requests.urllib3.request.urlencode(fields, safe=";")
AttributeError: 'function' object has no attribute 'urlencode'
```

**To Reproduce**
1. follow steps here: https://codeforces.com/blog/entry/74291
2. run code listed above

**Expected behavior**
The error mentioned above will be raised

**Environment:**

- Python version: 3.10.12
- Module version: [2a5f8e8](https://github.com/VadVergasov/CodeforcesApiPy/commit/2a5f8e81efe8f9229c7f4fd797d0e53b240d27fb)
- OS version: Ubuntu 22.04

**Possible Solution**
I believe switching line 71 of api_request_maker.py: `api_signature += requests.urllib3.request.urlencode(fields, safe=";")` 
into
```
api_signature += urlencode(fields, safe=";")
```
with the addition of this module `from urllib.parse import urlencode`

completely solve this issue.

**Comment by jpz** [comment]
I have the same issue, Python 3.11

**Comment by SanjaySRocks** [comment]
getting same error, how to fix it without making change in module file.

**Comment by VadVergasov** [comment]
> getting same error, how to fix it without making change in module file.

Hello! Just fixed that, I'll release fixed version soon. Sorry for inconvenience!
